config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  resources :users
  get  '/signup',  to: 'users#new'
  resources :recipes
  resources :categories
  get '/homepage', to: 'static_pages#home'
  root 'static_pages#home'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  before_save{self.description = description.downcase}
  #attr_accessible :description, :instructions, :title, :category_id
  belongs_to :category
  belongs_to :user
  #attr_accessor :title,:description,:instructions
  validates :title, :presence => true
  validates :description, :presence => true
  validates :instructions, :presence => true
  validates :user_id, presence: true
  #validates :category_id, :presence => true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # GET /recipes
  # GET /recipes.json
  before_action :logged_in, only:[:new,:create]
  before_action :editable_recipe, only:[:edit,:update,:destroy]
  def recipe_params
    params.require(:recipe).permit(:description, :instructions, :title, :category_id)
  end

  def index
    @recipes = Recipe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    #@recipe = Recipe.new(recipe_params)
    @recipe=current_user.recipes.build(recipe_params)
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end
  private
    def editable_recipe
      unless Recipe.find(params[:id]).user_id==current_user.id|| current_user.admin?
        redirect_to root_url, notice: 'Non editable recipe!'
      end
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <%= f.label :category_id %>
  <%= select("recipe", "category_id", Category.all.collect{ |c| [ c.name, c.id] }) %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br />
    <%= f.text_area :instructions %>
  </div>
  <div class="actions">
    <%= f.submit data:{ confirm: "Are you sure?" } %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Instructions</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% if !@recipes.nil? then @recipes.each do |recipe| %>
  <tr>
    <td><%= recipe.title %></td>
    <td><%= recipe.description %></td>
    <td><%= recipe.instructions %></td>
    <td><%= recipe.category.name %></td>
    <td><%= link_to 'Show', recipe %></td>
    <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
    <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
<% end %>
</table>

<br />

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p>
  <b>Title:</b>
  <%= @recipe.title %>
</p>

<p>
  <b>Description:</b>
  <%= @recipe.description %>
</p>

<p>
  <b>Instructions:</b>
  <%= @recipe.instructions %>
</p>


<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>